### ISSUE TITLE
Working with CoreMIDI in Playgrounds

### ISSUE THREAD

**Issue by knagle** [genedelisa/Swift3MIDI#1]
Is it possible to work with CoreMIDI within a Swift 3 playground? I have adapted your code for a playground and seem to be able create a client and detect when new devices are added and disconnected, but once I have created an input port with MIDIInputPortCreateWithBlock and connected it to the available sources using MIDIPortConnectSource, I don't receive any MIDI packets to myMIDIReadBlock. The same code works fine in an iOS app, but running in a playground nothing happens.

**Comment by genedelisa** [comment]
I just added a quickly hacked playground.

It creates and  plays a MusicSequence.

It looks like you cannot create input ports in a playground. I get an error simply creating the input port.
Didn't you? 
It says:
Error: execution interrupted.

**Comment by knagle** [comment]
Thanks for such a quick response. I am seeing the same error as you when I run your playground and my own playground in the simulator on Xcode. The problem is I was testing on Playgrounds for Swift Beta on iOS 10. On that app the playground runs, gives no errors, but does not seem to create the input port either. It may just be a limitation of Playgrounds.
