### ISSUE TITLE
Is this working with final Xcode 8 and Swift 3 release

### ISSUE THREAD

**Issue by sinewavemultimedia** [genedelisa/Swift3MIDI#2]
I was wondering if everything is in order for the final release of Xcode 8 and Swift 3. I have not been able to try this yet, but enjoyed the swift 2 version.

Thanks

**Comment by genedelisa** [comment]
This does work with Xcode 8/Swift 3. I just forgot to update the version in the README.

I'm adding more things to this since it was a "first step". That will probably be a new project.
